export const SET_REGISTRATION_STATUS = 'SET_REGISTRATION_STATUS';
export const UPDATE_USER_DATA = 'UPDATE_USER_DATA';
export const POST_USER_DATA_REQUEST = 'POST_USER_DATA_REQUEST';
export const POST_USER_DATA_SUCCESS = 'POST_USER_DATA_SUCCESS';
export const POST_USER_DATA_FAILURE = 'POST_USER_DATA_FAILURE';
